#!/usr/bin/env bash
#CUDA_VISIBLE_DEVICES=0, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 2  --n_clusters 4  --config ./configs/example.json  &
#CUDA_VISIBLE_DEVICES=0, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 3  --n_clusters 6  --config ./configs/example.json  &
#CUDA_VISIBLE_DEVICES=0, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 4  --n_clusters 8  --config ./configs/example.json  &
#CUDA_VISIBLE_DEVICES=0, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 5  --n_clusters 10 --config ./configs/example.json  &
#CUDA_VISIBLE_DEVICES=2, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 6  --n_clusters 12 --config ./configs/example.json  &
#CUDA_VISIBLE_DEVICES=2, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 7  --n_clusters 14 --config ./configs/example.json  &
#CUDA_VISIBLE_DEVICES=2, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 8  --n_clusters 16 --config ./configs/example.json  &
#CUDA_VISIBLE_DEVICES=2, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 9  --n_clusters 20 --config ./configs/example.json  &
#CUDA_VISIBLE_DEVICES=1, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 10 --n_clusters 20 --config ./configs/example.json  &
#CUDA_VISIBLE_DEVICES=1, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 12 --n_clusters 20 --config ./configs/example.json  &
#CUDA_VISIBLE_DEVICES=1, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 14 --n_clusters 20 --config ./configs/example.json  &
#CUDA_VISIBLE_DEVICES=1, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 16 --n_clusters 20 --config ./configs/example.json  &
#CUDA_VISIBLE_DEVICES=1, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 18 --n_clusters 20 --config ./configs/example.json  &
#CUDA_VISIBLE_DEVICES=1, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 20 --n_clusters 20 --config ./configs/example.json  &
#CUDA_VISIBLE_DEVICES=3, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 25 --n_clusters 20 --config ./configs/example.json  &
#CUDA_VISIBLE_DEVICES=3, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 30 --n_clusters 20 --config ./configs/example.json  &
#CUDA_VISIBLE_DEVICES=3, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 35 --n_clusters 20 --config ./configs/example.json  &
#CUDA_VISIBLE_DEVICES=3, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 40 --n_clusters 20 --config ./configs/example.json  &
#CUDA_VISIBLE_DEVICES=3, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 45 --n_clusters 20 --config ./configs/example.json  &
#CUDA_VISIBLE_DEVICES=3, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 50 --n_clusters 20 --config ./configs/example.json
#CUDA_VISIBLE_DEVICES=0, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 60  --n_clusters 20 --config ./configs/example.json  &
#CUDA_VISIBLE_DEVICES=1, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 70  --n_clusters 20 --config ./configs/example.json  &
#CUDA_VISIBLE_DEVICES=2, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 80  --n_clusters 20 --config ./configs/example.json  &
#CUDA_VISIBLE_DEVICES=0, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 90  --n_clusters 20 --config ./configs/example.json  &
#CUDA_VISIBLE_DEVICES=1, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 100 --batch_size 2 --n_clusters 20 --config ./configs/example.json  &
#CUDA_VISIBLE_DEVICES=2, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 110  --n_clusters 20 --batch_size 2 --unroll_steps 2 --config ./configs/example.json  &
#CUDA_VISIBLE_DEVICES=0, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 120  --n_clusters 20 --batch_size 2 --unroll_steps 2 --config ./configs/example.json  &
#CUDA_VISIBLE_DEVICES=3, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 130  --n_clusters 20 --batch_size 2 --unroll_steps 2 --config ./configs/example.json
#CUDA_VISIBLE_DEVICES=3, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 140  --n_clusters 20 --batch_size 2 --unroll_steps 2 --config ./configs/example.json  &
CUDA_VISIBLE_DEVICES=3, python ./example.py --exp_name journal --run_name more_unroll_steps --channel_cardinality 150  --n_clusters 20 --batch_size 2 --batch_size_eval 2 --unroll_steps 2 --config ./configs/example.json  &
